### PR TITLE
Make base_color configurable

### PR DESCRIPTION
**Pull request by joshgoebel**
Can we please make base_color easier to configure?

### CODE REVIEW

**Comment by joshgoebel** [comment]
So no?

**Comment by jorgebucaran** [comment]
This PR was automatically closed because I changed the default branch to `main` and removed `master`. You are welcome to open a new PR. Please use: `metro_base_color` instead and make sure to add this information to the documentation. Thanks!

**Comment by joshgoebel** [comment]
Probably not likely to seeing how it sat for three years the first time. Was just wondering at the sudden closure out of the blue with no comment.

**Comment by jorgebucaran** [comment]
Metrofish is the continuation of and successor to Metro. I had to set this project aside for a long time to concentrate on other things, but I was finally able to port it to the latest architecture, so it should work with Fisher 4.x. While I can't promise much activity, I'm back, so feel free to circle back to the project whenever you like! 👋

**Pull request closed without merging**
