### PR TITLE
Added python virtual env to right prompt

### PR DESCRIPTION
**Pull request by finestructure**

### CODE REVIEW

**Comment by ghost** [comment]
@feinstruktur Thanks, I'd like to merge this, but can you send me a screenshot to see how it looks first?

**Comment by finestructure** [comment]
Sure, here you go

screen shot 2016-05-19 at 08 42 19
screen shot 2016-05-19 at 08 43 13

**Comment by finestructure** [comment]
As you can tell, I haven't bothered setting the iTerm colours to the ones in the plugin :)

**Comment by ghost** [comment]
Ah, I see, so VIRTUAL_ENV is just a label. 

In the case of Metro, we already use the right prompt (sparingly) for $status, time and jobs, so it would probably make more sense to put it on the left as another segment, before or after any existing hostinfo info. 

This does require getting familiar with how [segment](https://github.com/fisherman/segment) works, so unless you want to get down to it for a particular reason, I can promise to get this fixed in a few hours :)

TBH I didn't know VIRTUAL_ENV was such a simple thing, else I would have added it to all the other themes I've made

**Comment by finestructure** [comment]
Just had a look at segments, looks simple enough :) I've added it although the colours may not be great.

screen shot 2016-05-19 at 09 16 41

I'll leave it at that, because I suspect even if I were to match the current end segment it may need tweaking to look ok with other states (git dirty etc).

Just close the PR if you'd rather redo it, the main point for me was to fork it so I can tweak it without losing changes on each `fisher update`. (Or is there an easier way to extend/override a plugin other than fork and `fisher install https://github.com/feinstruktur/metro.git`?)

**Comment by brj** [comment]
Not bad at all. Don't remove your branch just yet. I'll checkout and pull from you locally and tidy things up when I get a chance.

Thanks @feinstruktur! :)

**Comment by finestructure** [comment]
Was cleaning up my open PRs and I believe this is outdated now - closing!

**Comment by jorgebucaran** [comment]
Thanks! I'm working on a rewrite.

**Pull request closed without merging**
